# -*- coding: utf-8 -*-
# Generated by Django 1.11.7 on 2017-11-18 18:48
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('myprofile', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Heart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
            ],
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('message', models.TextField()),
            ],
        ),
        migrations.CreateModel(
            name='Rate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('rate', models.IntegerField()),
            ],
        ),
        migrations.AddField(
            model_name='profile',
            name='user',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='rate',
            name='profile_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_from', to='myprofile.Profile'),
        ),
        migrations.AddField(
            model_name='rate',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='rate_to', to='myprofile.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='profile_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_from', to='myprofile.Profile'),
        ),
        migrations.AddField(
            model_name='message',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='message_to', to='myprofile.Profile'),
        ),
        migrations.AddField(
            model_name='heart',
            name='profile_from',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_from', to='myprofile.Profile'),
        ),
        migrations.AddField(
            model_name='heart',
            name='profile_to',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='heart_to', to='myprofile.Profile'),
        ),
    ]
